[package]
name = "bruteforce"
version = "1.0.0"
edition = "2021"

[dependencies]
zip = "7.4.0"
anyhow = "1.0.101"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
